name: qserver-connect
channels:
    - conda-forge
dependencies:
    - pip
    - python=3.12
    - pip:
          - grpcio
          - requests
          - pytest
          - black
          - pylint
          - tox
          - mypy
          - grpcio-tools
          - requests
          - qiskit==1.3.2
          - setuptools
          - types-setuptools
          - types-protobuf
          - types-requests
          - qiskit_qasm3_import
