name: qserver-connect
channels:
    - conda-forge
dependencies:
    - pip
    - python=3.12
    - pip:
          - grpcio
          - requests
          - pytest
          - grpcio-tools
          - requests
