# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jobs.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'jobs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\njobs.proto\"\x9d\x01\n\rJobProperties\x12\x18\n\x10resultTypeCounts\x18\x01 \x01(\x08\x12\x1b\n\x13resultTypeQuasiDist\x18\x02 \x01(\x08\x12\x18\n\x10resultTypeExpVal\x18\x03 \x01(\x08\x12\x17\n\x0ftargetSimulator\x18\x04 \x01(\t\x12\x15\n\x08metadata\x18\x05 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_metadata\"R\n\x07JobData\x12$\n\nproperties\x18\x01 \x01(\x0b\x32\x0e.JobPropertiesH\x00\x12\x13\n\tqasmChunk\x18\x02 \x01(\tH\x00\x42\x0c\n\nDataStream\"\x18\n\nPendingJob\x12\n\n\x02id\x18\x01 \x01(\t2+\n\x04Jobs\x12#\n\x06\x41\x64\x64Job\x12\x08.JobData\x1a\x0b.PendingJob\"\x00(\x01\x42\x1dZ\x1bgithub.com/Dpbm/jobs_serverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jobs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033github.com/Dpbm/jobs_server'
  _globals['_JOBPROPERTIES']._serialized_start=15
  _globals['_JOBPROPERTIES']._serialized_end=172
  _globals['_JOBDATA']._serialized_start=174
  _globals['_JOBDATA']._serialized_end=256
  _globals['_PENDINGJOB']._serialized_start=258
  _globals['_PENDINGJOB']._serialized_end=282
  _globals['_JOBS']._serialized_start=284
  _globals['_JOBS']._serialized_end=327
# @@protoc_insertion_point(module_scope)
