name: Build, Test and publish

on:
    push:
        branches:
            - '*'
        tags:
            - '*'

jobs:
    tox:
        name: Run Tox python-${{ matrix.version }} ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                version:
                    - '3.12'
                os:
                    - ubuntu-22.04
                    - ubuntu-22.04-arm

        permissions:
            contents: read

        steps:
            - name: setup server
              run: |
                  git clone https://github.com/Dpbm/qserver.git && \
                  sudo echo "172.18.0.30 ${{ secrets.HOST }}" | sudo tee -a /etc/hosts && \
                  cd qserver/certs && \
                  chmod +x generate-ci-certs.sh && \
                  ./generate-ci-certs.sh ${{ secrets.HOST }} && \
                  cd .. && \
                  DOMAIN=${{ secrets.HOST }} docker compose -f ./dev-compose.yml up -d --build && \
                  rm -rf qserver

            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.version }}

            - name: install dependencies
              run: |
                  pip install -r requirements.txt -r dev-requirements.txt

            - name: Run tox checks
              run: |
                export HOST=${{ secrets.HOST }} &&
                tox

    publish:
        name: Upload package to PYPI
        runs-on: ubuntu-24.04

        needs: tox

        if: startsWith(github.ref, 'refs/tags/')

        environment:
            name: pypi
            url: https://pypi.org/p/qserver_connect

        permissions:
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12.8

            - name: build package
              run: |
                  python3 -m pip install --upgrade build
                  python3 -m build

            - name: Publish to PYPI
              uses: pypa/gh-action-pypi-publish@release/v1
